# render.yaml
services:
  - type: web
    name: myapp
    env: ruby
    region: oregon # or your preferred region
    plan: free # or your plan
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: fc09faec31f83b5bd4db5ad8eb76420e # Replace with your config/master.key
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: SMTP_PASSWORD
        value: <your-smtp-password> # If using mailer
    preBuild:
      - apt-get update -y
      - apt-get install -y nodejs # Install Node.js

databases:
  - name: myapp-db
    region: oregon # Match your web service region