# Final render.yaml for Git
databases:
  - name: my_basecamp_db
    databaseName: basecamp
    user: basecamp
    plan: free

services:
  - type: web
    name: my_basecamp_2
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_basecamp_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false- key: WEB_CONCURRENCY
        value:
    preBuild:
      - apt-get update -y
      - apt-get install -y nodejs
