# render.yaml for my_basecamp_2 Rails app
databases:
  - name: my_basecamp_db
    databaseName: basecamp
    user: basecamp
    plan: free

services:
  - type: web
    name: my_basecamp_2
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"  # Verify this exists; see below if not
    startCommand: "bundle exec rails server -b 0.0.0.0 -p $PORT"
    preBuild:
      commands:
        - apt-get update -y
        - apt-get install -y nodejs
    preDeploy:
      commands:
        - npm install -g yarn
        - yarn install
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_basecamp_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false  # Set value in Render dashboard (e.g., 966dbd6cf25ba2c267edaf3fc1137dd1)
      - key: NODE_VERSION
        value: 16
      - key: WEB_CONCURRENCY
        value: 1  # Suitable for free tier
      - key: RAILS_ENV
        value: production