# render.yaml
services:
  - type: web
    name: my_basecamp_2
    env: ruby
    region: oregon
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        value: <your-master-key>
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: my_basecamp_db
          property: connectionString
      - key: SMTP_PASSWORD
        value: aliyuaminu3369@gmail.com
    preBuild:
      - apt-get update -y
      - apt-get install -y nodejs

databases:
  - name: my_basecamp_db
    region: oregon